{ pkgs, ... }: let
  userChrome = builtins.readFile ../../../configs/apps/librewolf/userChrome.css;

  overrides = ''
    // Generated by Home Manager.
    pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
    pref("webgl.disabled", true);
    pref("privacy.resistFingerprinting", true);
    pref("privacy.clearOnShutdown.history", true);
    pref("privacy.clearOnShutdown.cookies", true);
    pref("network.cookie.lifetimePolicy", 2);
    pref("browser.fullscreen.autohide", false);
  '';
in {
  programs.librewolf = {
    enable = true;
    profiles.default = {
      id = 0;
      name = "default";
      isDefault = true;
      userChrome = userChrome;

      search = {
        force = true;
        default = "OmniSearch";
        engines = {
          "OmniSearch" = {
            urls = [{
              template = "http://localhost:8087/search";
              params = [{
                name = "q";
                value = "{searchTerms}";
              }];
            }];
            icon = "http://localhost:8087/static/favicon.ico";
            updateInterval = 24 * 60 * 60 * 1000;
            definedAliases = ["@os"];
          };
        };
      };
    };
  };

  home.file.".librewolf/librewolf.overrides.cfg".text = overrides;
}
