{ pkgs, lib, ... }: let
  vars = import ../../vars.nix;
  userChrome = builtins.readFile ../../configs/apps/librewolf/userChrome.css;

  overrides = ''
    // Generated by Home Manager.
    pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
    pref("webgl.disabled", true);
    pref("privacy.resistFingerprinting", true);
    pref("privacy.clearOnShutdown.history", true);
    pref("privacy.clearOnShutdown.cookies", true);
    pref("network.cookie.lifetimePolicy", 2);
    pref("browser.fullscreen.autohide", false);
  '';

  gtkPackage = {
    dracula = pkgs.dracula-theme;
    caelus = pkgs.caelus-theme;
  }.${vars.systemTheme};
  iconPackage = {
    dracula = pkgs.dracula-icon-theme;
    caelus = pkgs.dracula-icon-theme;
  }.${vars.systemTheme};
in {
  # ── Bat ──────────────────────────────────────────────────────────────────────
  programs.bat = {
    enable = true;
    config.theme = "ansi";
  };

  # ── Fzf ──────────────────────────────────────────────────────────────────────
  programs.fzf = {
    enable = true;
    colors = {
      "bg"      = "#282a36";
      "bg+"     = "#44475a";
      "fg"      = "#f8f8f2";
      "fg+"     = "#f8f8f2";
      "hl"      = "#bd93f9";
      "hl+"     = "#bd93f9";
      "info"    = "#8be9fd";
      "marker"  = "#ff79c6";
      "prompt"  = "#bd93f9";
      "spinner" = "#ff79c6";
      "pointer" = "#ff79c6";
      "header"  = "#6272a4";
      "border"  = "#44475a";
      "query"   = "#f8f8f2";
    };
  };

  # ── LibreWolf ────────────────────────────────────────────────────────────────
  programs.librewolf = {
    enable = true;
    profiles.default = {
      id = 0;
      name = "default";
      isDefault = true;
      userChrome = userChrome;
      extensions = {
        packages = with pkgs.nur.repos.rycee.firefox-addons; [
          ublock-origin sponsorblock return-youtube-dislikes darkreader sidebery vimium
        ];
        force = true;
      };

      settings = {
        "extensions.autoDisableScopes" = 0;
      };

      search = {
        force = true;
        default = "OmniSearch";
        engines = {
          "OmniSearch" = {
            urls = [{
              template = "http://localhost:8087/search";
              params = [{
                name = "q";
                value = "{searchTerms}";
              }];
            }];
            icon = "http://localhost:8087/static/favicon.ico";
            updateInterval = 24 * 60 * 60 * 1000;
            definedAliases = ["@os"];
          };
        };
      };
    };
  };

  home.file.".librewolf/librewolf.overrides.cfg".text = overrides;

  # ── Pictures ─────────────────────────────────────────────────────────────────
  home.file."Pictures" = {
    source = ../../configs/desktop/Pictures;
    recursive = true;
  };

  # ── Theme (GTK/Qt) ───────────────────────────────────────────────────────────
  gtk = {
    enable = true;
    theme = {
      name = vars.theme;
      package = gtkPackage;
    };
    iconTheme = {
      name = vars.theme;
      package = iconPackage;
    };
    font = {
      name = vars.font;
      size = 10;
    };
    gtk2.force = true;
    gtk3.extraConfig.gtk-application-prefer-dark-theme = 1;
    gtk4.extraConfig.gtk-application-prefer-dark-theme = 1;
  };

  qt = {
    enable = true;
    platformTheme.name = "gtk";
    style = {
      name = vars.qtTheme;
      package = pkgs.adwaita-qt;
    };
  };

  dconf.settings."org/gnome/desktop/interface" = {
    color-scheme = "prefer-dark";
    gtk-theme = vars.theme;
    icon-theme = vars.theme;
    cursor-theme = vars.cursorTheme;
    cursor-size = vars.cursorSize;
    font-name = "${vars.font} 10";
  };

  home.pointerCursor = {
    name = vars.cursorTheme;
    size = vars.cursorSize;
    package = pkgs.catppuccin-cursors.mochaMauve;
    gtk.enable = true;
    x11.enable = true;
  };

  # ── User dirs ────────────────────────────────────────────────────────────────
  xdg.userDirs = {
    enable = true;
    createDirectories = true;
  };

  # ── Vencord / Vesktop ────────────────────────────────────────────────────────
  programs.vesktop = {
    enable = true;
    vencord.settings =
      (builtins.fromJSON (builtins.readFile ../../configs/apps/vesktop/settings.json)).settings;
  };

  # ── XDG config files ─────────────────────────────────────────────────────────
  xdg.configFile."dunst/dunstrc".source = ../../configs/apps/dunst/dunstrc;
  xdg.configFile."fuzzel/fuzzel.ini".source = ../../configs/apps/fuzzel/fuzzel.ini;
  xdg.configFile."yazi/theme.toml".source = ../../configs/apps/yazi/theme.toml;
  xdg.configFile."yazi/yazi.toml".source = ../../configs/apps/yazi/yazi.toml;
  xdg.configFile."yazi/keymap.toml".source = ../../configs/apps/yazi/keymap.toml;
  xdg.configFile."yazi/flavors/dracula.yazi/flavor.toml".source = ../../configs/apps/yazi/flavors/dracula.yazi/flavor.toml;
  xdg.configFile."yazi/flavors/dracula.yazi/tmtheme.xml".source = ../../configs/apps/yazi/flavors/dracula.yazi/tmtheme.xml;
  xdg.configFile."qutebrowser/config.py".source = ../../configs/apps/qutebrowser/config.py;
  xdg.configFile."librewolf/sidebery-sidebar.css".source = ../../configs/apps/librewolf/sidebery-sidebar.css;
  xdg.configFile."gtklock/style.css".source = ../../configs/apps/gtklock/style.css;
  xdg.configFile."xdg-desktop-portal/portals.conf".text = ''[preferred] default=gtk'';
  xdg.configFile."zellij/config.kdl".source = ../../configs/apps/zellij/config.kdl;
  xdg.configFile."alacritty/alacritty.toml".source = ../../configs/apps/alacritty/alacritty.toml;
  xdg.configFile."fcitx5/config".source = ../../configs/apps/fcitx5/config;
  xdg.configFile."fcitx5/profile".source = ../../configs/apps/fcitx5/profile;
  xdg.configFile."fcitx5/conf/punctuation.conf".source = ../../configs/apps/fcitx5/conf/punctuation.conf;
  xdg.configFile."fcitx5/conf/spell.conf".source = ../../configs/apps/fcitx5/conf/spell.conf;
  xdg.configFile."fcitx5/conf/keyboard.conf".source = ../../configs/apps/fcitx5/conf/keyboard.conf;
  xdg.configFile."fcitx5/conf/notifications.conf".source = ../../configs/apps/fcitx5/conf/notifications.conf;
  xdg.configFile."fcitx5/conf/chttrans.conf".source = ../../configs/apps/fcitx5/conf/chttrans.conf;
}
